param(
  [string]$SourceDir = "src-jsx",
  [string]$OutputFile = "dist/WorkflowAssist.jsx"
)

$ErrorActionPreference = "Stop"

$root = Split-Path -Parent $PSScriptRoot
$src = Join-Path $root $SourceDir
$out = Join-Path $root $OutputFile
$outDir = Split-Path -Parent $out

if (-not (Test-Path -LiteralPath $src)) {
  throw "Source directory not found: $src"
}

if (-not (Test-Path -LiteralPath $outDir)) {
  New-Item -ItemType Directory -Force -Path $outDir | Out-Null
}

$files = Get-ChildItem -LiteralPath $src -Filter "*.jsx" |
  Sort-Object Name

if ($files.Count -eq 0) {
  throw "No .jsx files found in: $src"
}

$utf8NoBom = New-Object System.Text.UTF8Encoding($false)
$builder = New-Object System.Text.StringBuilder

[void]$builder.AppendLine("/*")
[void]$builder.AppendLine(" * WorkflowAssist.jsx")
[void]$builder.AppendLine(" * Generated by scripts/build-jsx.ps1.")
[void]$builder.AppendLine(" * Edit files in src-jsx/ instead of this generated file.")
[void]$builder.AppendLine(" */")
[void]$builder.AppendLine("")

foreach ($file in $files) {
  [void]$builder.AppendLine("")
  [void]$builder.AppendLine("// ===== BEGIN " + $file.Name + " =====")
  [void]$builder.AppendLine([System.IO.File]::ReadAllText($file.FullName, [System.Text.Encoding]::UTF8))
  [void]$builder.AppendLine("// ===== END " + $file.Name + " =====")
}

$content = $builder.ToString().Replace("`r`n", "`n").Replace("`r", "`n")
[System.IO.File]::WriteAllText($out, $content, $utf8NoBom)
Write-Host "Built $OutputFile from $($files.Count) file(s)."

$configDir = Join-Path $outDir "WorkflowAssist"
if (-not (Test-Path -LiteralPath $configDir)) {
  New-Item -ItemType Directory -Force -Path $configDir | Out-Null
  Write-Host "Created config directory: $configDir"
}

$configSource = Join-Path $root "config"
if (Test-Path -LiteralPath $configSource) {
  Get-ChildItem -LiteralPath $configSource | ForEach-Object {
    $dest = Join-Path $configDir $_.Name
    if ((Test-Path -LiteralPath $_.FullName -PathType Container) -and (Test-Path -LiteralPath $dest)) {
      Remove-Item -LiteralPath $dest -Recurse -Force
    }
    Copy-Item -Path $_.FullName -Destination $dest -Force -Recurse
    Write-Host "  Copied preset: $($_.Name)"
  }
}
