param(
  [string]$SourceDir = "src-jsx",
  [string]$OutputFile = "dist/WorkflowAssist.jsx"
)

$ErrorActionPreference = "Stop"

$root = Split-Path -Parent $PSScriptRoot
$src = Join-Path $root $SourceDir
$out = Join-Path $root $OutputFile
$outDir = Split-Path -Parent $out

if (-not (Test-Path -LiteralPath $src)) {
  throw "Source directory not found: $src"
}

if (-not (Test-Path -LiteralPath $outDir)) {
  New-Item -ItemType Directory -Force -Path $outDir | Out-Null
}

$files = Get-ChildItem -LiteralPath $src -Filter "*.jsx" |
  Sort-Object Name

if ($files.Count -eq 0) {
  throw "No .jsx files found in: $src"
}

# Step 1: Convert SVG icons to base64 constants
$iconsScript = Join-Path (Join-Path $root "scripts") "convert-icons.js"
if (Test-Path -LiteralPath $iconsScript) {
  node $iconsScript
  if ($LASTEXITCODE -ne 0) {
    throw "Icon conversion failed (exit code: $LASTEXITCODE)"
  }
}

# Validate sort configs
$sortDir = Join-Path $root "config\sort"
$hasErrors = $false
if (Test-Path -LiteralPath $sortDir) {
  Get-ChildItem -LiteralPath $sortDir -Filter "*.json" | ForEach-Object {
    try {
      $config = Get-Content -LiteralPath $_.FullName -Raw -Encoding UTF8 | ConvertFrom-Json
      $errors = @()
      if ($config.required) {
        foreach ($req in $config.required) {
          if (-not $req.name -and -not $req.regex -and -not $req.size) {
            $errors += "  required 项缺少 name/regex/size 标识"
          }
          if ($req.count -and -not $req.regex) {
            $errors += "  required 项有 count 但无 regex"
          }
          if ($req.size -and ($req.size.Count -ne 2 -or $req.size[0] -notmatch '^\d+$' -or $req.size[1] -notmatch '^\d+$')) {
            $errors += "  required 项 size 应为 [宽, 高]"
          }
          if ($req.maxSize -and $req.maxSize -notmatch '^\d+(\.\d+)?\s*(b|kb|mb|gb)?$') {
            $errors += "  required 项 maxSize 应为数字或 '500kb'/'5mb' 格式"
          }
        }
      }
      if ($config.rename) {
        foreach ($rn in $config.rename) {
          if (-not $rn.to) {
            $errors += "  rename 项缺少 to"
          }
          if (-not $rn.match -and -not $rn.regex -and -not $rn.size) {
            $errors += "  rename 项缺少 match/regex/size 标识"
          }
          if ($rn.size -and ($rn.size.Count -ne 2 -or $rn.size[0] -notmatch '^\d+$' -or $rn.size[1] -notmatch '^\d+$')) {
            $errors += "  rename 项 size 应为 [宽, 高]"
          }
        }
      }
      if ($config.zip -and -not $config.zip.name) {
        $errors += "  zip 缺少 name"
      }
      if ($errors.Count -gt 0) {
        $hasErrors = $true
        Write-Host "  WARN $($_.Name)" -ForegroundColor Yellow
        $errors | ForEach-Object { Write-Host "    $_" -ForegroundColor Yellow }
      } else {
        Write-Host "  OK sort/$($_.Name)"
      }
    } catch {
      $hasErrors = $true
      Write-Host "  ERROR $($_.Name): $_" -ForegroundColor Red
    }
  }
}
if ($hasErrors) {
  Write-Host "Sort config validation complete with warnings." -ForegroundColor Yellow
}

$utf8NoBom = New-Object System.Text.UTF8Encoding($false)
$builder = New-Object System.Text.StringBuilder

[void]$builder.AppendLine("/*")
[void]$builder.AppendLine(" * WorkflowAssist.jsx")
[void]$builder.AppendLine(" * Generated by scripts/build-jsx.ps1.")
[void]$builder.AppendLine(" * Edit files in src-jsx/ instead of this generated file.")
[void]$builder.AppendLine(" */")
[void]$builder.AppendLine("")

foreach ($file in $files) {
  [void]$builder.AppendLine("")
  [void]$builder.AppendLine("// ===== BEGIN " + $file.Name + " =====")
  [void]$builder.AppendLine([System.IO.File]::ReadAllText($file.FullName, [System.Text.Encoding]::UTF8))
  [void]$builder.AppendLine("// ===== END " + $file.Name + " =====")
}

$content = $builder.ToString().Replace("`r`n", "`n").Replace("`r", "`n")
[System.IO.File]::WriteAllText($out, $content, $utf8NoBom)
Write-Host "Built $OutputFile from $($files.Count) file(s)."

$configDir = Join-Path $outDir "WorkflowAssist"
if (-not (Test-Path -LiteralPath $configDir)) {
  New-Item -ItemType Directory -Force -Path $configDir | Out-Null
  Write-Host "Created config directory: $configDir"
}

$configSource = Join-Path $root "config"
if (Test-Path -LiteralPath $configSource) {
  # 清理 dist 配置目录中的残留文件（config 删除后旧文件不应残留）
  Get-ChildItem -LiteralPath $configDir -Force | Remove-Item -Recurse -Force
  Get-ChildItem -LiteralPath $configSource | ForEach-Object {
    $dest = Join-Path $configDir $_.Name
    if ((Test-Path -LiteralPath $_.FullName -PathType Container) -and (Test-Path -LiteralPath $dest)) {
      Remove-Item -LiteralPath $dest -Recurse -Force
    }
    Copy-Item -Path $_.FullName -Destination $dest -Force -Recurse
    Write-Host "  Copied preset: $($_.Name)"
  }
}

# Step 4: Copy to AE ScriptUI Panels (if AE is installed)
$aeScriptUIPath = "C:\Program Files\Adobe\Adobe After Effects 2023\Support Files\Scripts\ScriptUI Panels"
if (Test-Path -LiteralPath $aeScriptUIPath) {
  $aeDest = Join-Path $aeScriptUIPath "WorkflowAssist.jsx"
  $isLink = $false
  if (Test-Path -LiteralPath $aeDest) {
    $item = Get-Item -LiteralPath $aeDest
    if ($item.Attributes -band [System.IO.FileAttributes]::ReparsePoint) {
      $isLink = $true
      Write-Host "  AE ScriptUI Panels: symbolic link exists, skipping copy"
    }
  }
  if (-not $isLink) {
    Copy-Item -Path $out -Destination $aeDest -Force
    Write-Host "  Copied to AE ScriptUI Panels"
  }
}
