const sharp = require('sharp');
const fs = require('fs');
const path = require('path');

const ICONS_DIR = path.resolve(__dirname, '..', 'icons');
const OUTPUT_FILE = path.resolve(__dirname, '..', 'src-jsx', '01a-icons.jsx');
const ICON_SIZE = 25;

function kebabToCamel(str) {
    return str.replace(/[-_ ](\w)/g, function(_, c) { return c.toUpperCase(); })
              .replace(/^(\w)/, function(_, c) { return c.toLowerCase(); });
}

function toSource(buf) {
    var result = '';
    for (var i = 0; i < buf.length; i++) {
        var b = buf[i];
        if (b === 0x0D) { result += '\\r'; }
        else if (b === 0x0A) { result += '\\n'; }
        else if (b === 0x09) { result += '\\t'; }
        else if (b === 0x5C) { result += '\\\\'; }
        else if (b === 0x22) { result += '\\"'; }
        else if (b >= 0x20 && b <= 0x7E) { result += String.fromCharCode(b); }
        else if (b >= 0x80) {
            var hex = b.toString(16).toUpperCase();
            result += '\\u00' + (hex.length === 1 ? '0' : '') + hex;
        }
        else {
            var hex = b.toString(16).toUpperCase();
            result += '\\x' + (hex.length === 1 ? '0' : '') + hex;
        }
    }
    return '"' + result + '"';
}

async function convert() {
    if (!fs.existsSync(ICONS_DIR)) {
        console.log('Icons directory not found:', ICONS_DIR);
        console.log('Skipping icon conversion.');
        return;
    }

    var files = fs.readdirSync(ICONS_DIR)
        .filter(function(f) { return /\.(svg|png)$/i.test(f); })
        .sort();

    if (files.length === 0) {
        console.log('No icon files found in', ICONS_DIR);
        return;
    }

    var lines = [
        '//',
        '// Auto-generated by scripts/convert-icons.js',
        '// Do not edit manually.',
        '// Edit source SVG files in icons/ and run the build script.',
        '//',
        'var ICON_DATA = {'
    ];

    for (var i = 0; i < files.length; i++) {
        var file = files[i];
        var ext = path.extname(file).toLowerCase();
        var key = kebabToCamel(path.basename(file, ext));
        var filePath = path.join(ICONS_DIR, file);
        var buf = fs.readFileSync(filePath);

        var pngBuf = await sharp(buf)
            .resize(ICON_SIZE, ICON_SIZE, { fit: 'contain', background: { r: 0, g: 0, b: 0, alpha: 0 } })
            .png()
            .toBuffer();

        var sourceStr = toSource(pngBuf);
        lines.push('  ' + key + ': ' + sourceStr + ',');
        console.log('  ' + file + ' → ' + key + ' (' + pngBuf.length + ' bytes)');
    }

    lines.push('};');
    lines.push('');

    fs.writeFileSync(OUTPUT_FILE, lines.join('\n'), 'utf8');
    console.log('\nWrote ' + OUTPUT_FILE + ' with ' + files.length + ' icon(s)');
}

convert().catch(function(err) {
    console.error('Error:', err.message);
    process.exit(1);
});
