const sharp = require('sharp');
const fs = require('fs');
const path = require('path');

const ICONS_DIR = path.resolve(__dirname, '..', 'icons');
const CONFIG_ICONS_DIR = path.resolve(__dirname, '..', 'config', '_icons');
const OUTPUT_FILE = path.resolve(__dirname, '..', 'src-jsx', '01a-icons.jsx');
const ICON_SIZE = 25;

function kebabToCamel(str) {
    return str.replace(/[-_ ](\w)/g, function(_, c) { return c.toUpperCase(); })
              .replace(/^(\w)/, function(_, c) { return c.toLowerCase(); });
}

async function convert() {
    if (!fs.existsSync(ICONS_DIR)) {
        console.log('Icons directory not found:', ICONS_DIR);
        console.log('Skipping icon conversion.');
        return;
    }

    var files = fs.readdirSync(ICONS_DIR)
        .filter(function(f) { return /\.(svg|png)$/i.test(f); })
        .sort();

    if (files.length === 0) {
        console.log('No icon files found in', ICONS_DIR);
        return;
    }

    var iconData = {};

    for (var i = 0; i < files.length; i++) {
        var file = files[i];
        var ext = path.extname(file).toLowerCase();
        var key = kebabToCamel(path.basename(file, ext));
        var filePath = path.join(ICONS_DIR, file);
        var buf = fs.readFileSync(filePath);

        var pngBuf = await sharp(buf)
            .resize(ICON_SIZE, ICON_SIZE, { fit: 'contain', background: { r: 0, g: 0, b: 0, alpha: 0 } })
            .png()
            .toBuffer();

        iconData[key] = 'data:image/png;base64,' + pngBuf.toString('base64');

        // Also write PNG file for runtime loading (ScriptUI.newImage doesn't support data URIs in AE)
        if (!fs.existsSync(CONFIG_ICONS_DIR)) {
            fs.mkdirSync(CONFIG_ICONS_DIR, { recursive: true });
        }
        fs.writeFileSync(path.join(CONFIG_ICONS_DIR, key + '.png'), pngBuf);
        console.log('  ' + file + ' → ' + key);
    }

    var lines = [
        '//',
        '// Auto-generated by scripts/convert-icons.js',
        '// Do not edit manually.',
        '// Edit source SVG files in icons/ and run the build script.',
        '//',
        'var ICON_DATA = ' + JSON.stringify(iconData, null, 2) + ';',
        ''
    ];

    fs.writeFileSync(OUTPUT_FILE, lines.join('\n'), 'utf8');
    console.log('\nWrote ' + OUTPUT_FILE + ' with ' + Object.keys(iconData).length + ' icon(s)');
}

convert().catch(function(err) {
    console.error('Error:', err.message);
    process.exit(1);
});
